### ISSUE TITLE
Release Rebel Tech v2.0.0

### ISSUE THREAD

**Issue by hemmer** [hemmer/rebel-tech-vcv#1]
![Screenshot 2022-01-13 at 17 32 35](https://user-images.githubusercontent.com/915048/149380055-3d3b551a-f7d9-41bc-a904-426ccf92593a.png)

Issue to track work for initial release of Rebel Tech

- [x] Core logic for all modules
  - [x] CLK
  - [x] Tonic
  - [x] Klasmata
  - [x] Stoicheia
  - [x] Logoi
  - [x] Phoreo
- [x] Verfiy CV control
- [x] Confirm license
  - [x] Plugin code
  - [x] Graphics
- [x] Feedback from Martin
- [x] Feedback from VCV users
- [x] (optional) black panel mode

**Comment by hemmer** [comment]
![Screenshot 2022-01-13 at 17 30 45](https://user-images.githubusercontent.com/915048/149380377-954825eb-dec0-49ef-867c-ec959e9f2c10.png)

Quick screengrab of calibrating Logoi.

**Comment by hemmer** [comment]
VCV Rack doesn't support bidirectional cables, so one of the clock multis on Logoi and Stocheia has been re-purposed to act as "clock thru".

**Comment by hemmer** [comment]
Max delay on my hardware unit for Logoi seems to be just over 500ms, factor of 2 out from the manual? Oscilliscope output 
![image](https://user-images.githubusercontent.com/915048/149471340-6bf3f34e-ecd6-421d-a0ec-283ef4498478.png)

**Comment by pingdynasty** [comment]
Possibly...! What happens if you add a positive CV amount to the manual setting?
I'll try to reproduce.

**Comment by hemmer** [comment]
> Possibly...! What happens if you add a positive CV amount to the manual setting? I'll try to reproduce.

Looks like it's maxing out at around that value. 

1. If main knob is at zero, increasing CV voltage maxes out at the same 500ms
2. If main knob is max, increasing CV doesn't add anything further

Easy enough to change in code,  just let me know your preference.

**Comment by hemmer** [comment]
Updated panel graphics to be slightly off white / more metalic. Also made Tonic graphic outline a bit more prominent. 

**Now**
![image](https://user-images.githubusercontent.com/915048/149652753-9c4169d3-4c29-4b45-9cc3-283ebb09dc6b.png)

**Before**
![Screenshot 2022-01-13 at 17 32 35](https://user-images.githubusercontent.com/915048/149380055-3d3b551a-f7d9-41bc-a904-426ccf92593a.png)

**Comment by hemmer** [comment]
Trying out a dark mode on branch `v2-with-dark-mode`. I think it's easiest not to be part of the initial 2.0.0 release, maybe a followup release.

![image](https://user-images.githubusercontent.com/915048/153164042-c5ad80c9-58ba-4a2e-b90a-99262f5644d9.png)

**Comment by hemmer** [comment]
The timing of CLK was slightly off, this was due to a slight loss of precision due to using integer logic for clock ticks. Replacing this with floating point calculations for the master clock fixes it (subclocks can still be integer based). 

**Before**: 
![image](https://user-images.githubusercontent.com/915048/153751851-8ab482d4-f074-432f-ae08-542c341e9591.png)

**After**:
![image](https://user-images.githubusercontent.com/915048/153751929-1f1f4709-fd02-4c8f-87a4-105743c95dcc.png)

**Comment by dromer** [comment]
That dark mode looks really nice :)

**Comment by hemmer** [comment]
Tonic now polyphonic:

https://user-images.githubusercontent.com/915048/158231903-15a88e9c-a8f7-46a6-a04b-ff378800c863.mov

**Comment by pingdynasty** [comment]
wow, how does that work??

**Comment by hemmer** [comment]
Cables in VCV can be polyphonic (up to N = 16). So here the 2x2 outputs of the MI Branches are being stitched up into a 4 channel polyphonic gate signal (you can tell because it's thicker + blue cable LED indicator). Tonic then just works like there are N copies (under the hood it uses simd to speed things up), so it outputs 4 channels of gates and CV (leading to chords / arpeggios etc). 

![image](https://user-images.githubusercontent.com/915048/158264317-51a8454a-c6c4-47f8-a014-00c356b39898.png)

**Comment by hemmer** [comment]
![plugin](https://user-images.githubusercontent.com/915048/158552067-40df744f-7517-412e-8488-ed7739053464.png)

New wheels (also softened dial ticks, and tweaked CLK jacks spacing for software ergonomics) :)

**Comment by hemmer** [comment]
Submitted to library: https://github.com/VCVRack/library/issues/723

**Comment by dromer** [comment]
Any idea when you will add the dark panels? ;)

**Comment by hemmer** [comment]
> Any idea when you will add the dark panels? ;)

Got a couple of other VCV irons in the fire so once they're dealt with (and the dust settles on this release).

**Comment by hemmer** [comment]
Now in the library 😃

@dromer - dark mode branch should be ready to have a play if you want
