### ISSUE TITLE
License issue of Stoicheia/Klasmata and Logoi

### ISSUE THREAD

**Issue by dromer** [hemmer/rebel-tech-vcv#2]
It seems that the Stoicheia/Klasmata and Logoi source do not specify `or any later version` so are currently stuck on `GPL-2.0`.
This means that the current license of this repository is incorrect.

It would be good to contact rebeltech about this to ask them to apply the `or any later version` clause so that you can re-license to `GPL-3.0-or-later`.

**Comment by falkTX** [comment]
I dont think that applies.
Is any code from https://github.com/pingdynasty/EuclideanSequencer used on this repo?

**Comment by pingdynasty** [comment]
thank you both, @dromer and @falkTX !

> Is any code from https://github.com/pingdynasty/EuclideanSequencer used on this repo?

I believe it is, but it is not a problem
@hemmer has my permission (as the original copyright holder) to publish this under the GPL v3.

**Comment by falkTX** [comment]
> @hemmer has my permission (as the original copyright holder) to publish this under the GPL v3.

That is great, probably deserves a mention on the readme or license file?

**Comment by hemmer** [comment]
@dromer / @falkTX - I guess I shouldn't have made this repo open to the public yet. As you can see on the release ticket, there is an outstanding issue to clarify the license. I'll close the repo to the public now.

**Comment by hemmer** [comment]
@pingdynasty - can you confirm you're happy with the license as described in LICENSE.md ? Note it's `gplv3-only` is that ok? If so feel free to close this issue.

**Comment by pingdynasty** [comment]
yes

**Comment by hemmer** [comment]
@dromer / @falkTX - if we want to license as `gplv3-or-later` is that also possible? Does it just need written permission from copyright holder (@pingdynasty) or do the old repos have to be explicitly relicensed? I'm afraid I don't know enough about licensing.

**Comment by dromer** [comment]
@hemmer this depends on the rights-holder, and is not up to us.
The original code is licensed GPLv2 without specifying possible later versions.

However you have now been granted to use the code under GPLv3, does that now mean that the code has been re-licensed under GPLv3? A bit confusing.

Anyway, for Cardinal project we need explicit `GPL-3.0-or-later` compatible license (GPLv2+/BSD/MIT/ISC/CC0 etc.), to ensure forward compatibility.

The "cleanest" would be to append `-or-later` to the original `GPL-2.0` as said in the first post and is typically done for legacy code-bases, but this is fully up to @pingdynasty

**Comment by pingdynasty** [comment]
@dromer if you assigned GPLv2+ to Cardinal then you would be compatible with all (four) GPL licenses ([ref](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility)). Then we could be writing and discussing code instead of this.

@hemmer can you please license this repo under GPLv2+?

**Comment by dromer** [comment]
@pingdynasty we may want to release as GPLv4 in the future, because of the inclusion of new clauses applicable to future legal issues. However this is up to @falkTX as he has written most of the code and set the license (and likely has a good reason for wanting GPL3 provisions on the code).

And I agree that all this licensing/legal stuff is super annoying and takes way too much time. In the case of Cardinal we want to do proper due diligence and take care of any such issues as much as possible, because we rely on a lot of upstream code and it should all be compatible. Sorry for taking away your time on this.

**Comment by falkTX** [comment]
Cardinal cannot be licensed under GPLv2 because it uses code that is GPLv3 (from VCVRack)
Adaptation of GPLv3 code must be GPLv3 as well, only exception being to "upgrade" the license to something else, say AGPL or GPLv4 if original license was GPLv3+

But GPLv2+, GPLv3+ and the eventual GPLv4+ can live nicely together. The license that applies to the final binary is the most restrictive one, so that would be GPLv4+ in this theoretic case.

The recent [movements from FSF regarding copilot](https://lwn.net/Articles/886129/) leads me to think GPLv4 is near

**Comment by hemmer** [comment]
OK so I think we're good for all if _this_ repo is licensed under `gpl-v2-or-later` as @pingdynasty has asked. Progressing on that basis.

**Comment by falkTX** [comment]
Much appreciated, thank you.
One question unrelated to this, do not want to put pressure, just curious: when do you expect the modules to be ready for widespread/stable usage? wondering for inclusion in cardinal if they can make it on March release, or better wait for something afterwards.
Thanks again!

**Comment by hemmer** [comment]
Mm, the idea is probably to have them gather a couple of weeks of feedback (plus time to respond to anything), so probably mid March? Maybe next version is easier.

**Comment by hemmer** [comment]
> Much appreciated, thank you. One question unrelated to this, do not want to put pressure, just curious: when do you expect the modules to be ready for widespread/stable usage? wondering for inclusion in cardinal if they can make it on March release, or better wait for something afterwards. Thanks again!

@falkTX - FYI this is now in the Rack library
