### ISSUE TITLE
Crashing Stoichea

### ISSUE THREAD

**Issue by firolightfog** [hemmer/rebel-tech-vcv#3]
I'm using Stoichea in VCV 2.0.6 under Windows. Fill Density B can crash the module if the value is changed by right-click & entering new value. 

<img width="261" alt="image" src="https://user-images.githubusercontent.com/34127628/166147243-6a63ae83-7538-4fac-a29c-2a6378d13c82.png">

All other knobs work as expected. Turning this knob (Fill Density B) also works fine. 

Best regards, Andras

**Comment by hemmer** [comment]
Thanks for the bug report, will take a look!

**Comment by hemmer** [comment]
Ah I think you're using an old build (the knob graphics are from a previous version). If you delete `RebelTech` from plugins folder and subscribe via the library and update, the latest version should have this already fixed. :)

**Comment by hemmer** [comment]
If this doesn't fix, feel free to re-open.

**Comment by firolightfog** [comment]
You're right. the error was on my side. 

Following your advice I deleted the plugin folder, downloaded it again and all good now.

Best regards, Andras
